connect:
  twitter:
    key: "hbiNg5D00liMFjtwLvGIw"
    secret: "z7zaKWPSxv76eydVbUhnnlNa3SD8yyzI2FKyZ3F5Hdw"
    label: "Twitter"
  facebook:
    key: "my_key"
    secret: "my_secret"
    label: "Facebook"
  google:
    key: "my_key"
    secret: "my_secret"
    label: "Google"
  yahoo:
    key: "my_key"
    secret: "my_secret"
    label: "Yahoo"
  myspace:
    key: "my_key"
    secret: "my_secret"
  vimeo:
    key: "my_key"
    secret: "my_secret"
  linked_in:
    key: "my_key"
    secret: "my_secret"
