shared: &shared
  adapter: postgresql
  encoding: utf8
  username: postgres

development:
  <<: *shared
  database: pixie_development

test:
  <<: *shared
  database: pixie_test

production:
  <<: *shared
  database: pixie_production
